### PR TITLE
Custom ripple color

### PR DESCRIPTION
**Pull request by IchigoKyger**
Added a CSS variable to set the ripple color throughout your entire web app.

### CODE REVIEW

**Comment by IchigoKyger** [comment]
Any update on this it looks like all the tests passed on the CI server.

**Comment by addyosmani** [comment]
From the Polymer G+ community:

> Isn't the paper-icon-button ripple's colour supposed to be changed with the foreground colour? At the moment it is stuck at a transparent black, instead of a transparent version of whatever I set the foreground to be. I have had this "issue" since Polymer 1.0. ﻿

which I believe inspired this change. Change LGTM, but deferring to @notwaldorf who is smarter at all things CSS custom properties :athletic_shoe:

**Comment by notwaldorf** [comment]
@addyosmani Just re: `paper-icon-button`, there's a `--paper-icon-button-ink-color` custom property for that (see demo: https://github.com/PolymerElements/paper-icon-button/blob/master/demo/index.html#L70). I don't think it changes automatically, though.

**Comment by IchigoKyger** [comment]
This would just give a consistent variable that can be used across all elements for all ripples. (Instead of one off variables such as --paper-icon-button-ink-color, --paper-tab-ink -OR- having to use shadow for paper-button, and paper-fab)

**Comment by notwaldorf** [comment]
Sorry I'm being slow on this -- I just want to test this doesn't break the various elements that use `[noink]`

**Comment by notwaldorf** [comment]
@IchigoKyger This looks great. Would you mind adding a "Styling" section to the ripple docs, like we do in other [elements](https://github.com/PolymerElements/paper-input/blob/master/paper-input-container.html#L67)? Thanks!

**Comment by cdata** [comment]
This PR is looking good, but it needs a rebase before it can be merged. I'm going to close it for now, but please re-open it after you have performed a rebase!

**Pull request closed without merging**
